# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'VanishBrowser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VanishBrowser
  # FFmpegKit公式は廃止されたため、コミュニティ版を使用
  pod 'ffmpeg-kit-ios-full-gpl', '6.0'

end
