# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'VanishBrowser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VanishBrowser
  pod 'ffmpeg-kit-ios-full', '~> 6.0'

end
